apiVersion: v1
kind: Service
metadata:
  name: {{ include "chris-ui.fullname" . }}
  labels:
    {{- include "chris-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "chris-ui.selectorLabels" . | nindent 4 }}
