# Default values for chris-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/fnndsc/chris_ui
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest-staging"
chris_ui_host: rc-live.tch.harvard.edu:31222
pfdcm_host: rc-live.tch.harvard.edu:31032

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8020
  nodePort: 31020

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000

autoscaling:
  enabled: false

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
